#!/bin/sh
# Launch the nysiris Nym mixnet client.
#
# Serves the bundled PWA on loopback and opens it in a Chromium app window.
# Extra arguments are forwarded to the launcher (see --help).
exec /usr/lib/nysiris/nysiris-launcher \
    --root /usr/lib/nysiris/web \
    "$@"
