import type { CapacitorConfig } from '@capacitor/cli';

/**
 * Capacitor config for shipping the same web build as an Android app.
 *
 * `npx cap add android && npm run android:sync` generates the native project
 * under `android/`. The manifest and network-security-config in that folder are
 * generated by Capacitor; the copies in this repo's `android/` directory show
 * the settings that matter for a mixnet client (no cleartext, no file access).
 */
const config: CapacitorConfig = {
  appId: 'app.example.nysiris',
  appName: 'nysiris',
  webDir: 'dist',
  server: {
    androidScheme: 'https',
  },
  android: {
    // Never allow cleartext HTTP inside the app.
    allowMixedContent: false,
    // Enable only during development.
    webContentsDebuggingEnabled: false,
  },
};

export default config;
